services:
  mysql8:
    image: mysql:8.0.29        # 使用 MySQL 8.0.29 官方镜像
    restart: always            # 容器退出时自动重启
    command: --default-authentication-plugin=mysql_native_password  # 使用旧版密码认证方式
    environment:
      MYSQL_ROOT_PASSWORD: root  # 设置 root 用户密码
    volumes:
      #volumes 部分将本地的 ./script/mysql/ 目录挂载到容器的 /docker-entrypoint-initdb.d/ 目录。
      - ./script/mysql/:/docker-entrypoint-initdb.d/  # 挂载初始化 SQL 脚本
    ports:
      - "13316:3306"           # 将容器 3306 端口映射到宿主机 13316 端口

  redis:
    image: bitnami/redis:latest  # 使用 Bitnami 的 Redis 镜像
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  # 允许空密码（无密码访问）
    ports:
      - '6379:6379'             # 映射 Redis 默认端口